name: Build Firmware

on:
  workflow_dispatch:  # ðŸ‘ˆ æ·»åŠ è¿™ä¸€è¡Œ
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile firmware
      run: |
        chmod +x compile-with-docker.sh
        ./compile-with-docker.sh all

    - name: Show generated files (debug)
      run: ls -la compiled-firmware/

    - name: Upload all firmware binaries
      uses: actions/upload-artifact@v4
      with:
        name: f4hwn-firmware-all
        path: compiled-firmware/
